org: fernandomcsea
app: serverless-surveys
service: test-surveys

provider:
  name: aws
  runtime: python3.8
  environment:
    DYNAMODB_TABLE: test-surveys-${opt:stage, self:provider.stage}
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:GetItem
      Resource:
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  createCustomer:
    handler: src/handlers/create_customer_handler.handler
    events:
      - http:
          path: /customer
          method: post
  getCustomer:
    handler: src/handlers/get_customer_handler.handler
    events:
      - http:
          path: /customer/{customer_id}
          method: get
  createSurvey:
    handler: src/handlers/create_survey_handler.handler
    events:
      - http:
          path: /survey
          method: post
  getCustomerSurvey:
    handler: src/handlers/get_survey_handler.handler
    events:
      - httpApi:
          path: /customer-survey
          method: get
  getAllCustomerSurveys:
    handler: src/handlers/get_all_customer_surveys_handler.handler
    events:
      - http:
          path: customer/{customer_id}/surveys
          method: get
  createSurveyResponse:
    handler: src/handlers/create_response_handler.handler
    events:
      - http:
          path: /response
          method: post
  getSurveyResponse:
    handler: src/handlers/get_survey_handler.handler
    events:
      - http:
          path: survey/{survey_id}/response/{response_id}
          method: get
  getAllSurveyResponses:
    handler: src/handlers/get_all_survey_responses_handler.handler
    events:
      - http:
          path: survey/{survey_id}/responses
          method: get

resources:
  Resources:
    surveysTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - venv/**
    - __pycache__/**
    - tests/**
    - .vscode/**
    - .pytest_cache/**
    - conftest.py