name: Python Pull Request Workflow
on: [pull_request]
env: 
  TEST_AUTH0_CLIENT_SECRET: ${{ secrets.TEST_AUTH0_CLIENT_SECRET }}
jobs:

  qa:
    name: Quality check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Run unit tests
        run: |
          pip install -r test-requirements.txt
          pytest tests/unit
      - name: Run integration tests
        run: |
          pip install -r test-requirements.txt
          pytest tests/integration
      - name: Generate coverage report
        run: |
          pip install -r test-requirements.txt
          pytest --cov=./ --cov-report=xml
      - name: Codecov
        uses: codecov/codecov-action@v1.0.7
        with:
          file: ./coverage.xml
          flags: unittests
