name: Python Pull Request Workflow
on: [pull_request]
env: 
  TEST_AUTH0_CLIENT_SECRET: ${{ secrets.TEST_AUTH0_CLIENT_SECRET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
jobs:

  qa:
    name: Quality check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Run unit tests
        run: |
          pip install -r test-requirements.txt
          pytest tests/unit
      - name: Run integration tests
        run: |
          pip install -r test-requirements.txt
          pytest tests/integration
      - name: Generate coverage report
        run: |
          pip install -r test-requirements.txt
          pytest --cov=./ --cov-report=xml
      - name: Codecov
        uses: codecov/codecov-action@v1.0.7
        with:
          file: ./coverage.xml
          flags: unittests
